# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - ./volume:/tf
    environment:
      MYSQL_ROOT_PASSWORD: datascience
    ports:
        - 9996:33060

  tensor:
    #image: tensorflow/tensorflow:latest-jupyter
    build: ./docker_tf
    restart: always
    volumes:
        - ./volume:/tf
        - /home/andrew:/tf/home
    environment:
        - PASSWORD=motion
        - JUPYTER_TOKEN=motion
    ports:
      - "10101:8888"
      - "80:80"
      

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: datascience

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: datascience
      ME_CONFIG_MONGODB_URL: mongodb://root:datascience@mongo:27017/
